"""Token usage tracking for local and API-based LLM classifiers.

Usage
-----
    from folktexts import TokenTracker

    tracker = TokenTracker(model_name="my-model", output_path="tokens.jsonl")

    # Inside a training/inference loop:
    tracker.record_batch(prompt_tokens=512, completion_tokens=64, batch_size=8)

    print(tracker)          # human-readable summary
    print(tracker.get_stats())  # dict of totals
    tracker.save("final_tokens.jsonl")  # explicit save of all records
"""

from __future__ import annotations

import json
import logging
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path


@dataclass
class _BatchRecord:
    """Record for a single batch of model calls."""

    timestamp: str
    model_name: str
    prompt_tokens: int
    completion_tokens: int
    batch_size: int


class TokenTracker:
    """Tracks token usage across model inference calls.

    Works with both local (transformers) and web-API classifiers. Counts are
    accumulated per-batch and can optionally be persisted to a JSONL file
    (one record per line) as they arrive.
    """

    def __init__(
        self,
        model_name: str = "",
        output_path: str | Path | None = None,
    ):
        """Create a TokenTracker.

        Parameters
        ----------
        model_name : str, optional
            Name of the model being tracked. Stored in every record.
        output_path : str | Path, optional
            Path to a JSONL file for streaming writes. Records are appended as
            they come in. If *None*, records are kept in memory only and can be
            written later with :meth:`save`.
        """
        self.model_name = model_name
        self.output_path = Path(output_path) if output_path else None

        self._records: list[_BatchRecord] = []
        self._total_prompt_tokens: int = 0
        self._total_completion_tokens: int = 0
        self._num_batches: int = 0

    # ------------------------------------------------------------------
    # Recording
    # ------------------------------------------------------------------

    def record_batch(
        self,
        prompt_tokens: int,
        completion_tokens: int = 0,
        batch_size: int = 1,
        model_name: str | None = None,
    ) -> None:
        """Record token usage for a single batch.

        Parameters
        ----------
        prompt_tokens : int
            Number of input (prompt) tokens consumed by the batch.
        completion_tokens : int, optional
            Number of output (completion) tokens generated by the batch.
        batch_size : int, optional
            Number of prompts in the batch.
        model_name : str, optional
            Per-call model name override; falls back to ``self.model_name``.
        """
        record = _BatchRecord(
            timestamp=datetime.now(tz=timezone.utc).isoformat(),
            model_name=model_name or self.model_name,
            prompt_tokens=prompt_tokens,
            completion_tokens=completion_tokens,
            batch_size=batch_size,
        )
        self._records.append(record)
        self._total_prompt_tokens += prompt_tokens
        self._total_completion_tokens += completion_tokens
        self._num_batches += 1

        if self.output_path is not None:
            self._append_record(record)

        logging.debug(
            "[TokenTracker] batch %d — prompt=%d  completion=%d  total_so_far=%d",
            self._num_batches,
            prompt_tokens,
            completion_tokens,
            self.total_tokens,
        )

    def _append_record(self, record: _BatchRecord) -> None:
        """Append *record* to the JSONL output file."""
        if self.output_path is None:
            return
        try:
            self.output_path.parent.mkdir(parents=True, exist_ok=True)
            with self.output_path.open("a", encoding="utf-8") as fh:
                fh.write(json.dumps(asdict(record)) + "\n")
        except OSError as exc:
            logging.warning("[TokenTracker] Could not write to %s: %s", self.output_path, exc)

    # ------------------------------------------------------------------
    # Properties
    # ------------------------------------------------------------------

    @property
    def total_prompt_tokens(self) -> int:
        """Total prompt (input) tokens across all recorded batches."""
        return self._total_prompt_tokens

    @property
    def total_completion_tokens(self) -> int:
        """Total completion (output) tokens across all recorded batches."""
        return self._total_completion_tokens

    @property
    def total_tokens(self) -> int:
        """Total tokens (prompt + completion) across all recorded batches."""
        return self._total_prompt_tokens + self._total_completion_tokens

    @property
    def num_batches(self) -> int:
        """Number of batches recorded so far."""
        return self._num_batches

    # ------------------------------------------------------------------
    # Output
    # ------------------------------------------------------------------

    def get_stats(self) -> dict:
        """Return a summary dict of token usage statistics."""
        return {
            "model_name": self.model_name,
            "num_batches": self._num_batches,
            "total_prompt_tokens": self._total_prompt_tokens,
            "total_completion_tokens": self._total_completion_tokens,
            "total_tokens": self.total_tokens,
        }

    def save(self, path: str | Path) -> None:
        """Write all in-memory records to *path* (JSONL, overwrites).

        Parameters
        ----------
        path : str | Path
            Destination file path. Parent directories are created as needed.
        """
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("w", encoding="utf-8") as fh:
            for record in self._records:
                fh.write(json.dumps(asdict(record)) + "\n")
        logging.info("[TokenTracker] Saved %d records to %s", len(self._records), path)

    def reset(self) -> None:
        """Clear all accumulated counts and records."""
        self._records.clear()
        self._total_prompt_tokens = 0
        self._total_completion_tokens = 0
        self._num_batches = 0

    def __str__(self) -> str:
        return (
            f"TokenTracker(model={self.model_name!r})\n"
            f"  Batches:            {self._num_batches}\n"
            f"  Prompt tokens:      {self._total_prompt_tokens:,}\n"
            f"  Completion tokens:  {self._total_completion_tokens:,}\n"
            f"  Total tokens:       {self.total_tokens:,}"
        )

    def __repr__(self) -> str:
        return (
            f"TokenTracker(model={self.model_name!r}, "
            f"batches={self._num_batches}, "
            f"total_tokens={self.total_tokens})"
        )
